spring.application.name=employee-management-spring
# PostgreSQL接続設定
spring.datasource.url=jdbc:postgresql://localhost:5432/Sampledb

spring.datasource.username=postgres

spring.datasource.password=NSCo68081

# JDBCドライバー
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA設定
spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true